<a href="https://colab.research.google.com/github/Marianill/ProyectosCienciaDatos/blob/main/Dataset_clima_tareas_carga_limpieza_transformacion_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Se trabaja con el dataset "datos_clima.csv"

##### El dataset fue previamente cargado en el drive con permisos necesarios para ser descargado

## Importamos dependencias

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt

## Se descarga dataset

In [2]:
url = "https://drive.google.com/uc?id=1S_e5v1UnIPeumoqMqCAiQG2MUg0m8qDg"
nombre_descarga = "datos_clima.csv"

In [3]:
!wget {url} -O {nombre_descarga}

--2023-11-21 21:48:43--  https://drive.google.com/uc?id=1S_e5v1UnIPeumoqMqCAiQG2MUg0m8qDg
Resolving drive.google.com (drive.google.com)... 74.125.199.139, 74.125.199.101, 74.125.199.100, ...
Connecting to drive.google.com (drive.google.com)|74.125.199.139|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-0g-24-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/1krp3vq4516ioteoqajq30l2vitaqtul/1700603250000/16220715687418982044/*/1S_e5v1UnIPeumoqMqCAiQG2MUg0m8qDg?uuid=5aea8a0a-9c69-41a3-91c6-a93571a3c330 [following]
Warning: wildcards not supported in HTTP.
--2023-11-21 21:48:44--  https://doc-0g-24-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/1krp3vq4516ioteoqajq30l2vitaqtul/1700603250000/16220715687418982044/*/1S_e5v1UnIPeumoqMqCAiQG2MUg0m8qDg?uuid=5aea8a0a-9c69-41a3-91c6-a93571a3c330
Resolving doc-0g-24-docs.googleusercontent.com (doc-0g-24-docs.googleusercontent.com)... 74.125.195.132, 2607:f8b0:400e:c09::84
Connecting to doc-0g-24-docs.googleusercontent.com (doc-0g-24-docs.googleusercontent.com)|74.125.195.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2761 (2.7K) [text/csv]
Saving to: ‘datos_clima.csv’

datos_clima.csv     100%[===================>]   2.70K  --.-KB/s    in 0s

2023-11-21 21:48:44 (164 MB/s) - ‘datos_clima.csv’ saved [2761/2761]

## Ejecución de comandos de entorno para inspeccionar archivo "datos_clima.csv"

### El comando "ls -l" lista los archivos con sus permisos, usuario, grupo, tamaño, fecha de creación y nombre.

In [4]:
!ls -l

total 8
-rw-r--r-- 1 root root 2761 Nov 21 19:45 datos_clima.csv
drwxr-xr-x 1 root root 4096 Nov 20 14:42 sample_data

### El comando "head" muestra las primeras 10 líneas del archivo

In [5]:
!head datos_clima.csv

FECHA,HORA,,TEMP,HUM,PNM,DD,FF,estacion met.,,,,NOMBRE
19/03/2023,0,,8.2,86,1515.0,190,9,BARILOCHE_AERO,,,,
19/03/2023,1,,8.1,84,1516.0,200,9,BARILOCHE_AERO,,,,
19/03/2023,2,,8.3,82,1515.0,190,9,BARILOCHE_AERO,,,,
19/03/2023,3,,8.3,80,1514.0,200,7,BARILOCHE_AERO,,,,
19/03/2023,4,,7.8,79,1512.0,200,9,BARILOCHE_AERO,,,,
19/03/2023,5,,7.2,83,1509.0,200,11,BARILOCHE_AERO,,,,
19/03/2023,6,,6.6,78,1511.0,200,9,BARILOCHE_AERO,,,,
19/03/2023,7,,6.2,81,1510.0,190,9,BARILOCHE_AERO,,,,
19/03/2023,8,,6.5,77,1507.0,180,13,BARILOCHE_AERO,,,,

### El comando "cat" muestra el contenido del archivo

In [6]:
!cat datos_clima.csv

FECHA,HORA,,TEMP,HUM,PNM,DD,FF,estacion met.,,,,NOMBRE
19/03/2023,0,,8.2,86,1515.0,190,9,BARILOCHE_AERO,,,,
19/03/2023,1,,8.1,84,1516.0,200,9,BARILOCHE_AERO,,,,
19/03/2023,2,,8.3,82,1515.0,190,9,BARILOCHE_AERO,,,,
19/03/2023,3,,8.3,80,1514.0,200,7,BARILOCHE_AERO,,,,
19/03/2023,4,,7.8,79,1512.0,200,9,BARILOCHE_AERO,,,,
19/03/2023,5,,7.2,83,1509.0,200,11,BARILOCHE_AERO,,,,
19/03/2023,6,,6.6,78,1511.0,200,9,BARILOCHE_AERO,,,,
19/03/2023,7,,6.2,81,1510.0,190,9,BARILOCHE_AERO,,,,
19/03/2023,8,,6.5,77,1507.0,180,13,BARILOCHE_AERO,,,,
19/03/2023,8,,6.5,77,1507.0,180,13,BARILOCHE_AERO,,,,
19/03/2023,9,,6.9,70,1507.0,200,9,BARILOCHE_AERO,,,,
19/03/2023,10,,10.1,71,1509.0,190,6,BARILOCHE_AERO,,,,
19/03/2023,11,,12.3,63,1512.0,990,6,BARILOCHE_AERO,,,,
19/03/2023,12,,13.7,57,1511.0,290,11,BARILOCHE_AERO,,,,
19/03/2023,13,,14.9,41,1507.0,300,13,BARILOCHE_AERO,,,,
19/03/2023,14,,17.1,38,1501.0,320,19,BARILOCHE_AERO,,,,
19/03/2023,15,,18.9,27,1499.0,320,20,BARILOCHE_AERO,,,,
19/03/2023,16,,20.1,20,1494.0,300,24,BARILOCHE_AERO,,,,
19/03/2023,17,,20.3,18,1493.0,300,33,BARILOCHE_AERO,,,,
19/03/2023,18,,19.4,30,1489.0,280,30,BARILOCHE_AERO,,,,
19/03/2023,19,,18.8,25,1488.0,300,28,BARILOCHE_AERO,,,,
19/03/2023,20,,15.6,47,1491.0,300,17,BARILOCHE_AERO,,,,
19/03/2023,21,,14.1,46,1499.0,140,6,BARILOCHE_AERO,,,,
19/03/2023,22,,10.5,46,1506.0,200,9,BARILOCHE_AERO,,,,
19/03/2023,23,,8.2,62,1513.0,110,13,BARILOCHE_AERO,,,,
19/03/2023,0,,27.6,53,1007.2,50,26,CATAMARCA_AERO,,,,
19/03/2023,0,,27.6,53,1007.2,50,26,CATAMARCA_AERO,,,,
19/03/2023,1,,27.2,50,1006.9,20,28,CATAMARCA_AERO,,,,
19/03/2023,2,,26.4,54,1006.6,20,26,CATAMARCA_AERO,,,,
19/03/2023,3,,,52,1006.1,20,31,CATAMARCA_AERO,,,,
19/03/2023,4,,,52,1005.8,20,30,CATAMARCA_AERO,,,,
19/03/2023,5,,26.6,58,1005.9,20,17,CATAMARCA_AERO,,,,
19/03/2023,6,,24.8,60,1006.6,340,9,CATAMARCA_AERO,,,,
19/03/2023,7,,24.2,63,1007.2,360,11,CATAMARCA_AERO,,,,
19/03/2023,8,,23.2,62,1008.5,20,6,CATAMARCA_AERO,,,,
19/03/2023,9,,25.8,57,1009.2,0,0,CATAMARCA_AERO,,,,
19/03/2023,10,,28.8,43,1007.6,,,CATAMARCA_AERO,,,,
19/03/2023,11,,30.2,43,1009.6,,9,CATAMARCA_AERO,,,,
19/03/2023,12,,32.8,40,1008.4,,4,CATAMARCA_AERO,,,,
19/03/2023,13,,35.6,32,1006.9,,9,CATAMARCA_AERO,,,,
19/03/2023,14,,37.0,30,1005.7,20,11,CATAMARCA_AERO,,,,
19/03/2023,15,,37.0,29,1004.8,20,17,CATAMARCA_AERO,,,,
19/03/2023,16,,38.8,24,1003.4,20,11,CATAMARCA_AERO,,,,
19/03/2023,17,,38.6,24,1002.9,20,17,CATAMARCA_AERO,,,,
19/03/2023,18,,36.8,27,1003.2,20,24,CATAMARCA_AERO,,,,
19/03/2023,19,,34.8,32,1004.0,20,26,CATAMARCA_AERO,,,,
19/03/2023,20,,32.8,39,1004.9,20,20,CATAMARCA_AERO,,,,
19/03/2023,21,,31.4,42,1005.2,20,22,CATAMARCA_AERO,,,,
19/03/2023,22,,30.1,42,1006.1,20,19,CATAMARCA_AERO,,,,
19/03/2023,23,,29.2,43,1006.7,20,15,CATAMARCA_AERO,,,,

## Se carga el archivo "datos_clima.csv" en un dataframe y se muestra su contenido

### Se lee el archivo "datos_clima.csv" y se guarda en la variable clima

In [7]:
clima = pd.read_csv("datos_clima.csv")
clima

,FECHA,HORA,Unnamed: 2,TEMP,HUM,PNM,DD,FF,estacion met.,Unnamed: 9,Unnamed: 10,Unnamed: 11,NOMBRE
0,19/03/2023,0,NaN,8.2,86,1515.0,190.0,9.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
1,19/03/2023,1,NaN,8.1,84,1516.0,200.0,9.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
2,19/03/2023,2,NaN,8.3,82,1515.0,190.0,9.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
3,19/03/2023,3,NaN,8.3,80,1514.0,200.0,7.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
4,19/03/2023,4,NaN,7.8,79,1512.0,200.0,9.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
5,19/03/2023,5,NaN,7.2,83,1509.0,200.0,11.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
6,19/03/2023,6,NaN,6.6,78,1511.0,200.0,9.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
7,19/03/2023,7,NaN,6.2,81,1510.0,190.0,9.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
8,19/03/2023,8,NaN,6.5,77,1507.0,180.0,13.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
9,19/03/2023,8,NaN,6.5,77,1507.0,180.0,13.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
10,19/03/2023,9,NaN,6.9,70,1507.0,200.0,9.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
11,19/03/2023,10,NaN,10.1,71,1509.0,190.0,6.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
12,19/03/2023,11,NaN,12.3,63,1512.0,990.0,6.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
13,19/03/2023,12,NaN,13.7,57,1511.0,290.0,11.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
14,19/03/2023,13,NaN,14.9,41,1507.0,300.0,13.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
15,19/03/2023,14,NaN,17.1,38,1501.0,320.0,19.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
16,19/03/2023,15,NaN,18.9,27,1499.0,320.0,20.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
17,19/03/2023,16,NaN,20.1,20,1494.0,300.0,24.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
18,19/03/2023,17,NaN,20.3,18,1493.0,300.0,33.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
19,19/03/2023,18,NaN,19.4,30,1489.0,280.0,30.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
20,19/03/2023,19,NaN,18.8,25,1488.0,300.0,28.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
21,19/03/2023,20,NaN,15.6,47,1491.0,300.0,17.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
22,19/03/2023,21,NaN,14.1,46,1499.0,140.0,6.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
23,19/03/2023,22,NaN,10.5,46,1506.0,200.0,9.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
24,19/03/2023,23,NaN,8.2,62,1513.0,110.0,13.0,BARILOCHE_AERO,NaN,NaN,NaN,NaN
25,19/03/2023,0,NaN,27.6,53,1007.2,50.0,26.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
26,19/03/2023,0,NaN,27.6,53,1007.2,50.0,26.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
27,19/03/2023,1,NaN,27.2,50,1006.9,20.0,28.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
28,19/03/2023,2,NaN,26.4,54,1006.6,20.0,26.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
29,19/03/2023,3,NaN,NaN,52,1006.1,20.0,31.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
30,19/03/2023,4,NaN,NaN,52,1005.8,20.0,30.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
31,19/03/2023,5,NaN,26.6,58,1005.9,20.0,17.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
32,19/03/2023,6,NaN,24.8,60,1006.6,340.0,9.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
33,19/03/2023,7,NaN,24.2,63,1007.2,360.0,11.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
34,19/03/2023,8,NaN,23.2,62,1008.5,20.0,6.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
35,19/03/2023,9,NaN,25.8,57,1009.2,0.0,0.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
36,19/03/2023,10,NaN,28.8,43,1007.6,NaN,NaN,CATAMARCA_AERO,NaN,NaN,NaN,NaN
37,19/03/2023,11,NaN,30.2,43,1009.6,NaN,9.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
38,19/03/2023,12,NaN,32.8,40,1008.4,NaN,4.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
39,19/03/2023,13,NaN,35.6,32,1006.9,NaN,9.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
40,19/03/2023,14,NaN,37.0,30,1005.7,20.0,11.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
41,19/03/2023,15,NaN,37.0,29,1004.8,20.0,17.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
42,19/03/2023,16,NaN,38.8,24,1003.4,20.0,11.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
43,19/03/2023,17,NaN,38.6,24,1002.9,20.0,17.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
44,19/03/2023,18,NaN,36.8,27,1003.2,20.0,24.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
45,19/03/2023,19,NaN,34.8,32,1004.0,20.0,26.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
46,19/03/2023,20,NaN,32.8,39,1004.9,20.0,20.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
47,19/03/2023,21,NaN,31.4,42,1005.2,20.0,22.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
48,19/03/2023,22,NaN,30.1,42,1006.1,20.0,19.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN
49,19/03/2023,23,NaN,29.2,43,1006.7,20.0,15.0,CATAMARCA_AERO,NaN,NaN,NaN,NaN

## Se muestra las columnas con sus tipos de datos del dataframe

In [8]:
clima.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   FECHA          50 non-null     object
 1   HORA           50 non-null     int64
 2   Unnamed: 2     0 non-null      float64
 3   TEMP           48 non-null     float64
 4   HUM            50 non-null     int64
 5   PNM            50 non-null     float64
 6   DD             46 non-null     float64
 7   FF             49 non-null     float64
 8   estacion met.  50 non-null     object
 9   Unnamed: 9     0 non-null      float64
 10  Unnamed: 10    0 non-null      float64
 11  Unnamed: 11    0 non-null      float64
 12  NOMBRE         0 non-null      float64
dtypes: float64(9), int64(2), object(2)
memory usage: 5.2+ KB

## Eliminación de las columnas que tienen todos los valores nulos

### Se eliminan columnas que tengan todos los valores nulos y se guarda el dataframe obtenido en una nueva variable

In [9]:
climaSinValsNull = clima.dropna(axis="columns", how="all")

In [10]:
climaSinValsNull

         FECHA  HORA  TEMP  HUM     PNM     DD    FF   estacion met.
0   19/03/2023     0   8.2   86  1515.0  190.0   9.0  BARILOCHE_AERO
1   19/03/2023     1   8.1   84  1516.0  200.0   9.0  BARILOCHE_AERO
2   19/03/2023     2   8.3   82  1515.0  190.0   9.0  BARILOCHE_AERO
3   19/03/2023     3   8.3   80  1514.0  200.0   7.0  BARILOCHE_AERO
4   19/03/2023     4   7.8   79  1512.0  200.0   9.0  BARILOCHE_AERO
5   19/03/2023     5   7.2   83  1509.0  200.0  11.0  BARILOCHE_AERO
6   19/03/2023     6   6.6   78  1511.0  200.0   9.0  BARILOCHE_AERO
7   19/03/2023     7   6.2   81  1510.0  190.0   9.0  BARILOCHE_AERO
8   19/03/2023     8   6.5   77  1507.0  180.0  13.0  BARILOCHE_AERO
9   19/03/2023     8   6.5   77  1507.0  180.0  13.0  BARILOCHE_AERO
10  19/03/2023     9   6.9   70  1507.0  200.0   9.0  BARILOCHE_AERO
11  19/03/2023    10  10.1   71  1509.0  190.0   6.0  BARILOCHE_AERO
12  19/03/2023    11  12.3   63  1512.0  990.0   6.0  BARILOCHE_AERO
13  19/03/2023    12  13.7   57  1511.0  290.0  11.0  BARILOCHE_AERO
14  19/03/2023    13  14.9   41  1507.0  300.0  13.0  BARILOCHE_AERO
15  19/03/2023    14  17.1   38  1501.0  320.0  19.0  BARILOCHE_AERO
16  19/03/2023    15  18.9   27  1499.0  320.0  20.0  BARILOCHE_AERO
17  19/03/2023    16  20.1   20  1494.0  300.0  24.0  BARILOCHE_AERO
18  19/03/2023    17  20.3   18  1493.0  300.0  33.0  BARILOCHE_AERO
19  19/03/2023    18  19.4   30  1489.0  280.0  30.0  BARILOCHE_AERO
20  19/03/2023    19  18.8   25  1488.0  300.0  28.0  BARILOCHE_AERO
21  19/03/2023    20  15.6   47  1491.0  300.0  17.0  BARILOCHE_AERO
22  19/03/2023    21  14.1   46  1499.0  140.0   6.0  BARILOCHE_AERO
23  19/03/2023    22  10.5   46  1506.0  200.0   9.0  BARILOCHE_AERO
24  19/03/2023    23   8.2   62  1513.0  110.0  13.0  BARILOCHE_AERO
25  19/03/2023     0  27.6   53  1007.2   50.0  26.0  CATAMARCA_AERO
26  19/03/2023     0  27.6   53  1007.2   50.0  26.0  CATAMARCA_AERO
27  19/03/2023     1  27.2   50  1006.9   20.0  28.0  CATAMARCA_AERO
28  19/03/2023     2  26.4   54  1006.6   20.0  26.0  CATAMARCA_AERO
29  19/03/2023     3   NaN   52  1006.1   20.0  31.0  CATAMARCA_AERO
30  19/03/2023     4   NaN   52  1005.8   20.0  30.0  CATAMARCA_AERO
31  19/03/2023     5  26.6   58  1005.9   20.0  17.0  CATAMARCA_AERO
32  19/03/2023     6  24.8   60  1006.6  340.0   9.0  CATAMARCA_AERO
33  19/03/2023     7  24.2   63  1007.2  360.0  11.0  CATAMARCA_AERO
34  19/03/2023     8  23.2   62  1008.5   20.0   6.0  CATAMARCA_AERO
35  19/03/2023     9  25.8   57  1009.2    0.0   0.0  CATAMARCA_AERO
36  19/03/2023    10  28.8   43  1007.6    NaN   NaN  CATAMARCA_AERO
37  19/03/2023    11  30.2   43  1009.6    NaN   9.0  CATAMARCA_AERO
38  19/03/2023    12  32.8   40  1008.4    NaN   4.0  CATAMARCA_AERO
39  19/03/2023    13  35.6   32  1006.9    NaN   9.0  CATAMARCA_AERO
40  19/03/2023    14  37.0   30  1005.7   20.0  11.0  CATAMARCA_AERO
41  19/03/2023    15  37.0   29  1004.8   20.0  17.0  CATAMARCA_AERO
42  19/03/2023    16  38.8   24  1003.4   20.0  11.0  CATAMARCA_AERO
43  19/03/2023    17  38.6   24  1002.9   20.0  17.0  CATAMARCA_AERO
44  19/03/2023    18  36.8   27  1003.2   20.0  24.0  CATAMARCA_AERO
45  19/03/2023    19  34.8   32  1004.0   20.0  26.0  CATAMARCA_AERO
46  19/03/2023    20  32.8   39  1004.9   20.0  20.0  CATAMARCA_AERO
47  19/03/2023    21  31.4   42  1005.2   20.0  22.0  CATAMARCA_AERO
48  19/03/2023    22  30.1   42  1006.1   20.0  19.0  CATAMARCA_AERO
49  19/03/2023    23  29.2   43  1006.7   20.0  15.0  CATAMARCA_AERO

## Identificación de filas duplicadas y eliminación de las mismas

### Identificación de filas duplicadas

In [11]:
climaSinValsNull.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26     True
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

### Eliminación de filas duplicadas y asignación en un nuevo dataframe

In [12]:
climaSinDuplic = climaSinValsNull.drop_duplicates()

In [13]:
climaSinDuplic

         FECHA  HORA  TEMP  HUM     PNM     DD    FF   estacion met.
0   19/03/2023     0   8.2   86  1515.0  190.0   9.0  BARILOCHE_AERO
1   19/03/2023     1   8.1   84  1516.0  200.0   9.0  BARILOCHE_AERO
2   19/03/2023     2   8.3   82  1515.0  190.0   9.0  BARILOCHE_AERO
3   19/03/2023     3   8.3   80  1514.0  200.0   7.0  BARILOCHE_AERO
4   19/03/2023     4   7.8   79  1512.0  200.0   9.0  BARILOCHE_AERO
5   19/03/2023     5   7.2   83  1509.0  200.0  11.0  BARILOCHE_AERO
6   19/03/2023     6   6.6   78  1511.0  200.0   9.0  BARILOCHE_AERO
7   19/03/2023     7   6.2   81  1510.0  190.0   9.0  BARILOCHE_AERO
8   19/03/2023     8   6.5   77  1507.0  180.0  13.0  BARILOCHE_AERO
10  19/03/2023     9   6.9   70  1507.0  200.0   9.0  BARILOCHE_AERO
11  19/03/2023    10  10.1   71  1509.0  190.0   6.0  BARILOCHE_AERO
12  19/03/2023    11  12.3   63  1512.0  990.0   6.0  BARILOCHE_AERO
13  19/03/2023    12  13.7   57  1511.0  290.0  11.0  BARILOCHE_AERO
14  19/03/2023    13  14.9   41  1507.0  300.0  13.0  BARILOCHE_AERO
15  19/03/2023    14  17.1   38  1501.0  320.0  19.0  BARILOCHE_AERO
16  19/03/2023    15  18.9   27  1499.0  320.0  20.0  BARILOCHE_AERO
17  19/03/2023    16  20.1   20  1494.0  300.0  24.0  BARILOCHE_AERO
18  19/03/2023    17  20.3   18  1493.0  300.0  33.0  BARILOCHE_AERO
19  19/03/2023    18  19.4   30  1489.0  280.0  30.0  BARILOCHE_AERO
20  19/03/2023    19  18.8   25  1488.0  300.0  28.0  BARILOCHE_AERO
21  19/03/2023    20  15.6   47  1491.0  300.0  17.0  BARILOCHE_AERO
22  19/03/2023    21  14.1   46  1499.0  140.0   6.0  BARILOCHE_AERO
23  19/03/2023    22  10.5   46  1506.0  200.0   9.0  BARILOCHE_AERO
24  19/03/2023    23   8.2   62  1513.0  110.0  13.0  BARILOCHE_AERO
25  19/03/2023     0  27.6   53  1007.2   50.0  26.0  CATAMARCA_AERO
27  19/03/2023     1  27.2   50  1006.9   20.0  28.0  CATAMARCA_AERO
28  19/03/2023     2  26.4   54  1006.6   20.0  26.0  CATAMARCA_AERO
29  19/03/2023     3   NaN   52  1006.1   20.0  31.0  CATAMARCA_AERO
30  19/03/2023     4   NaN   52  1005.8   20.0  30.0  CATAMARCA_AERO
31  19/03/2023     5  26.6   58  1005.9   20.0  17.0  CATAMARCA_AERO
32  19/03/2023     6  24.8   60  1006.6  340.0   9.0  CATAMARCA_AERO
33  19/03/2023     7  24.2   63  1007.2  360.0  11.0  CATAMARCA_AERO
34  19/03/2023     8  23.2   62  1008.5   20.0   6.0  CATAMARCA_AERO
35  19/03/2023     9  25.8   57  1009.2    0.0   0.0  CATAMARCA_AERO
36  19/03/2023    10  28.8   43  1007.6    NaN   NaN  CATAMARCA_AERO
37  19/03/2023    11  30.2   43  1009.6    NaN   9.0  CATAMARCA_AERO
38  19/03/2023    12  32.8   40  1008.4    NaN   4.0  CATAMARCA_AERO
39  19/03/2023    13  35.6   32  1006.9    NaN   9.0  CATAMARCA_AERO
40  19/03/2023    14  37.0   30  1005.7   20.0  11.0  CATAMARCA_AERO
41  19/03/2023    15  37.0   29  1004.8   20.0  17.0  CATAMARCA_AERO
42  19/03/2023    16  38.8   24  1003.4   20.0  11.0  CATAMARCA_AERO
43  19/03/2023    17  38.6   24  1002.9   20.0  17.0  CATAMARCA_AERO
44  19/03/2023    18  36.8   27  1003.2   20.0  24.0  CATAMARCA_AERO
45  19/03/2023    19  34.8   32  1004.0   20.0  26.0  CATAMARCA_AERO
46  19/03/2023    20  32.8   39  1004.9   20.0  20.0  CATAMARCA_AERO
47  19/03/2023    21  31.4   42  1005.2   20.0  22.0  CATAMARCA_AERO
48  19/03/2023    22  30.1   42  1006.1   20.0  19.0  CATAMARCA_AERO
49  19/03/2023    23  29.2   43  1006.7   20.0  15.0  CATAMARCA_AERO

## Identificación de valores nulos

In [14]:
climaSinDuplic.isna()

    FECHA   HORA   TEMP    HUM    PNM     DD     FF  estacion met.
0   False  False  False  False  False  False  False          False
1   False  False  False  False  False  False  False          False
2   False  False  False  False  False  False  False          False
3   False  False  False  False  False  False  False          False
4   False  False  False  False  False  False  False          False
5   False  False  False  False  False  False  False          False
6   False  False  False  False  False  False  False          False
7   False  False  False  False  False  False  False          False
8   False  False  False  False  False  False  False          False
10  False  False  False  False  False  False  False          False
11  False  False  False  False  False  False  False          False
12  False  False  False  False  False  False  False          False
13  False  False  False  False  False  False  False          False
14  False  False  False  False  False  False  False          False
15  False  False  False  False  False  False  False          False
16  False  False  False  False  False  False  False          False
17  False  False  False  False  False  False  False          False
18  False  False  False  False  False  False  False          False
19  False  False  False  False  False  False  False          False
20  False  False  False  False  False  False  False          False
21  False  False  False  False  False  False  False          False
22  False  False  False  False  False  False  False          False
23  False  False  False  False  False  False  False          False
24  False  False  False  False  False  False  False          False
25  False  False  False  False  False  False  False          False
27  False  False  False  False  False  False  False          False
28  False  False  False  False  False  False  False          False
29  False  False   True  False  False  False  False          False
30  False  False   True  False  False  False  False          False
31  False  False  False  False  False  False  False          False
32  False  False  False  False  False  False  False          False
33  False  False  False  False  False  False  False          False
34  False  False  False  False  False  False  False          False
35  False  False  False  False  False  False  False          False
36  False  False  False  False  False   True   True          False
37  False  False  False  False  False   True  False          False
38  False  False  False  False  False   True  False          False
39  False  False  False  False  False   True  False          False
40  False  False  False  False  False  False  False          False
41  False  False  False  False  False  False  False          False
42  False  False  False  False  False  False  False          False
43  False  False  False  False  False  False  False          False
44  False  False  False  False  False  False  False          False
45  False  False  False  False  False  False  False          False
46  False  False  False  False  False  False  False          False
47  False  False  False  False  False  False  False          False
48  False  False  False  False  False  False  False          False
49  False  False  False  False  False  False  False          False

## Reemplazo valores nulos por cero

### Reemplazo de valores nulos por ceros y asignación en un nuevo dataframe

In [15]:
climaReempCeros = climaSinDuplic.fillna(0)

### Verificación de reemplazo de valores nulos por ceros

In [16]:
climaReempCeros.isna()

    FECHA   HORA   TEMP    HUM    PNM     DD     FF  estacion met.
0   False  False  False  False  False  False  False          False
1   False  False  False  False  False  False  False          False
2   False  False  False  False  False  False  False          False
3   False  False  False  False  False  False  False          False
4   False  False  False  False  False  False  False          False
5   False  False  False  False  False  False  False          False
6   False  False  False  False  False  False  False          False
7   False  False  False  False  False  False  False          False
8   False  False  False  False  False  False  False          False
10  False  False  False  False  False  False  False          False
11  False  False  False  False  False  False  False          False
12  False  False  False  False  False  False  False          False
13  False  False  False  False  False  False  False          False
14  False  False  False  False  False  False  False          False
15  False  False  False  False  False  False  False          False
16  False  False  False  False  False  False  False          False
17  False  False  False  False  False  False  False          False
18  False  False  False  False  False  False  False          False
19  False  False  False  False  False  False  False          False
20  False  False  False  False  False  False  False          False
21  False  False  False  False  False  False  False          False
22  False  False  False  False  False  False  False          False
23  False  False  False  False  False  False  False          False
24  False  False  False  False  False  False  False          False
25  False  False  False  False  False  False  False          False
27  False  False  False  False  False  False  False          False
28  False  False  False  False  False  False  False          False
29  False  False  False  False  False  False  False          False
30  False  False  False  False  False  False  False          False
31  False  False  False  False  False  False  False          False
32  False  False  False  False  False  False  False          False
33  False  False  False  False  False  False  False          False
34  False  False  False  False  False  False  False          False
35  False  False  False  False  False  False  False          False
36  False  False  False  False  False  False  False          False
37  False  False  False  False  False  False  False          False
38  False  False  False  False  False  False  False          False
39  False  False  False  False  False  False  False          False
40  False  False  False  False  False  False  False          False
41  False  False  False  False  False  False  False          False
42  False  False  False  False  False  False  False          False
43  False  False  False  False  False  False  False          False
44  False  False  False  False  False  False  False          False
45  False  False  False  False  False  False  False          False
46  False  False  False  False  False  False  False          False
47  False  False  False  False  False  False  False          False
48  False  False  False  False  False  False  False          False
49  False  False  False  False  False  False  False          False

## Generación de medidas descriptivas

In [17]:
climaReempCeros.describe()

            HORA       TEMP        HUM          PNM          DD         FF
count  48.000000  48.000000  48.000000    48.000000   48.000000  48.000000
mean   11.500000  20.162500  50.875000  1255.779167  153.333333  14.937500
std     6.995439  11.331159  19.632393   252.273948  173.295140   8.613217
min     0.000000   0.000000  18.000000  1002.900000    0.000000   0.000000
25%     5.750000   8.300000  36.500000  1006.475000   20.000000   9.000000
50%    11.500000  19.750000  48.500000  1248.800000  160.000000  12.000000
75%    17.250000  29.425000  63.000000  1507.500000  220.000000  20.500000
max    23.000000  38.800000  86.000000  1516.000000  990.000000  33.000000